FROM golang:1.24-alpine AS build
WORKDIR /app
COPY main.go go.mod ./
RUN go mod download
RUN go build -o /app/bin .

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/bin .
ENTRYPOINT ["/app/bin"]
