FROM alpine:3.14

WORKDIR /app

COPY go.mod . 
COPY main.go . 

RUN wget https://go.dev/dl/go1.24.5.linux-amd64.tar.gz
RUN rm -rf /usr/local/go 
RUN tar -C /usr/local -xzf go1.24.5.linux-amd64.tar.gz
RUN export PATH=$PATH:/usr/local/go/bin
RUN echo $PATH
RUN /usr/local/go/bin/go build -o bin .

ENTRYPOINT [ "/app/bin" ]
